# Generated by Django 3.0.4 on 2020-03-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='オブジェクト名')),
                ('obj_code', models.CharField(max_length=32, verbose_name='コード')),
            ],
            options={
                'verbose_name': 'オブジェクト名',
                'verbose_name_plural': 'オブジェクト名',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=32, verbose_name='ブランチ名')),
                ('branch_code', models.CharField(max_length=32, verbose_name='ブランチコード')),
                ('obj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Obj')),
            ],
            options={
                'verbose_name': 'ブランチ名',
                'verbose_name_plural': 'ブランチ名',
            },
        ),
    ]
